# Generated by Django 4.1.5 on 2023-01-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
